# Generated by Django 2.2.28 on 2022-10-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelabelconfig',
            name='bundle_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id приложения в appstore'),
        ),
        migrations.AddField(
            model_name='whitelabelconfig',
            name='push_bundle_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id пуш экстеншена в appstore'),
        ),
    ]
